name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Using 3.8 for better compatibility
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib numpy>=1.8 packaging parameterized pandas>=1.4 tqdm
          # Install pyEpiabm in development mode to ensure it's in PYTHONPATH
          git clone https://github.com/SABS-R3-Epidemiology/epiabm.git
          cd epiabm
          pip install -e .
          cd ..

      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          brew install pkg-config
          
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::reticulate
            
      - name: Configure reticulate
        run: |
          echo "RETICULATE_PYTHON=$(which python)" >> $GITHUB_ENV
          mkdir -p ~/.Renviron
          echo "RETICULATE_PYTHON=$(which python)" >> ~/.Renviron
          
      - name: Check Python configuration
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import sys; print(sys.path)"
          python -c "import pyEpiabm; print('pyEpiabm found')" || echo "pyEpiabm not found"
          
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
          check-dir: check